[package]
name = "riscv-rust-quickstart"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.3"
hifive1 = { version = "0.6.0", features = ["board-hifive1-revb"] }
panic-halt = "0.2.0"
riscv = "0.5.2"
riscv-rt = "0.5.0"

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
